### ISSUE TITLE
cmake .. report error

### ISSUE THREAD

**Issue by code7** [YuzukiTsuru/OpenixCard#2]
~/project/d1s/OpenixCard/build$ cmake ..
CMake Error at CMakeLists.txt:43 (add_subdirectory):
  The source directory

    /home/tom/project/d1s/OpenixCard/lib/inicpp

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:44 (add_subdirectory):
  The source directory

    /home/tom/project/d1s/OpenixCard/lib/argparse

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:45 (add_subdirectory):
  The source directory

    /home/tom/project/d1s/OpenixCard/lib/ftxui

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/tom/project/d1s/OpenixCard/build/CMakeFiles/CMakeOutput.log".
See also "/home/tom/project/d1s/OpenixCard/build/CMakeFiles/CMakeError.log".

**Comment by YuzukiTsuru** [comment]
Please according to the documentation to compile it.

```
git clone --recursive https://github.com/YuzukiTsuru/OpenixCard


..or

git clone https://github.com/YuzukiTsuru/OpenixCard
git submdoule init
git submodule update
```

Projects are managed through submodules. When you clone, you need to clone them all. You cannot simply download zip.
