### ISSUE TITLE
feature: support android image

### ISSUE THREAD

**Issue by YuzukiTsuru** [YuzukiTsuru/OpenixCard#29]

**Comment by leoneii** [comment]
> 

Hi
Unable to pack or convert android image.

![2022-09-21_20-38_1](https://user-images.githubusercontent.com/8148374/191574557-26060a8b-c397-4f0c-b93d-dab877cb89f8.png)
![2022-09-21_20-38](https://user-images.githubusercontent.com/8148374/191574560-2d239d6b-ea96-46db-acf0-5184fa738ee1.png)
![2022-09-21_20-43](https://user-images.githubusercontent.com/8148374/191574564-ee688a8b-c766-4413-9513-cec0a64d03f4.png)
