### ISSUE TITLE
How to use this to flash an SD-Card image to Onboard NAND?

### ISSUE THREAD

**Issue by deftdawg** [YuzukiTsuru/OpenixCard#30]
Forgive me if this is a dumb question, but a solution wasn't obvious to me looking at the command line switches.

How would one take an SD image from https://github.com/johang/sd-card-images created like this:
```sh
wget http://dl.sd-card-images.johang.se/boots/2022-12-01/boot-pcduino3_nano.bin.gz
wget http://dl.sd-card-images.johang.se/debians/2022-12-12/debian-bookworm-armhf-eaha4y.bin.gz
zcat boot-pcduino3_nano.bin.gz debian-bookworm-armhf-eaha4y.bin.gz > sd-card.img
```

And convert `sd-card.img` into a format that it would flash onto the internal NAND of an AllWinner A20 when booted? (I have a PCDuino3 Nano)

**Comment by YuzukiTsuru** [comment]
Writing to on-board storage requires chip and software support. This software cannot do such things

**Comment by D3VL-Jack** [comment]
@deftdawg Did you figure this step out?
When using a PhoenixCard compatible image and burning it to a microSD with PhoenixCard's "Work Type" set to "Product", it will copy the contents to the internal storage of the device on boot.

@YuzukiTsuru is there any support or method to convert images like this, from a "regular image" back to an "Allwinner image"?
