### ISSUE TITLE
cubieboard4 (sunxi a80) gen sdcard img

### ISSUE THREAD

**Issue by Nigelwz** [YuzukiTsuru/OpenixCard#42]
I use cubieboard4 (sunxi a80), I generate a img from sdk, I need to use it to generate a sdcard image.
But I saw the below message, do I need to change anything?

```bash
[GenIMG ERROR]: file(boot_package.fex): stat(/home/nigel/opensource/OpenixCard/build/dist/sun9iw1p1_linux_cubieboard4.img.dump/boot_package.fex) failed: No such file or directory
```

**Comment by YuzukiTsuru** [comment]
This platform is too old and the generated images are not supported

**Comment by Nigelwz** [comment]
If I want to support this platform, how to modify code? maybe I can send a patch for  this repostory.

**Comment by YuzukiTsuru** [comment]
You can try to delete the boot_package.fex section in OpenixCard -uc generated .cfg file and pack with OpenixCard
