### ISSUE TITLE
Not Allwinner image

### ISSUE THREAD

**Issue by commonuserlol** [YuzukiTsuru/OpenixCard#46]
Tried unpack A13 board android image but got `[OpenixCard ERROR] File: S101-A_2.4.10_120908-1.img is not Allwinner image.`

```
> OpenixCard -u S101-A_2.4.10_120908-1.img
...
[OpenixCard INFO] Converting input file: S101-A_2.4.10_120908-1.img
[OpenixIMG INFO] Decrypting IMG header...
[OpenixIMG INFO] IMG version is: 0x462a224
[OpenixCard ERROR] File: S101-A_2.4.10_120908-1.img is not Allwinner image.
```

I can upload image to some file hosting (github won't allow 300MB) if you need that

**Comment by YuzukiTsuru** [comment]
Android image not support by openixcard
