### ISSUE TITLE
Generated img file can't be used on etcher

### ISSUE THREAD

**Issue by benjamimgois** [YuzukiTsuru/OpenixCard#49]
Hi ! I'm trying to generate a image of OrangePi_Android on Arch Linux and just discovered openixcard. I installed the latest version from the AUR and used to command 

**openixCard -d OrangePi_Zero3_Android12_v1.0.img**

The original image is 1.2GB and the generated image is 3.4GB, so i guess openixcard did it's magic. Unfortunatly the i got an error when trying to write it to my SD on balena etcher.

![image](https://github.com/user-attachments/assets/1393c0bd-13d1-45e2-b438-c542e7f05b5a)

What am i doing wrong ?

Thanks for you work !

**Comment by lis6502** [comment]
As for Etcher - i would launch it from command line to obtain all goodies over STDERR which you might miss.
As for generated image - not OrangePI but opencardix generates perfectly `dd`'able images for my Lichee RV.
Unless dd fails i'd file a bug rather to Etcher than Opencardix

**Comment by YuzukiTsuru** [comment]
OpenixCard not support **any** Android image. The private gpt table issue cannot be resolved

**Comment by benjamimgois** [comment]
Thanks for the infor @YuzukiTsuru , so the problem is with the private gpt table. So, i guess i'll have to virtualize windows. Thanks for the help !
