### ISSUE TITLE
Problems with creating an image of android (alwinner)

### ISSUE THREAD

**Issue by agevlakh** [YuzukiTsuru/OpenixCard#6]
Hi, friend! First of all, I want to thank you for your efforts in creating this program! But I'm having problems. I compiled your program from the sources for Fedora 36. When executing commands with the program, the problem is that I do not create a new image. Unfortunately, the program itself does not show errors, but I made a video in which this error is visible in the file manager. Please check out this video. It is possible that I am doing something wrong, but I watched a [video](https://www.youtube.com/watch?v=hgX6R27LZAY) in which this problem is not. I tried the program with several android images for orange pi (h3 and h616), but to no avail. Thanks
OpenixCard version for me:
```
[anton@cerebro OpenixCard]$ ./OpenixCard -v
 _____             _     _____           _ 
|     |___ ___ ___|_|_ _|     |___ ___ _| |
|  |  | . | -_|   | |_'_|   --| .'|  _| . |
|_____|  _|___|_|_|_|_,_|_____|__,|_| |___|
      |_| Version: 3e34a8c
Copyright (c) 2022, YuzukiTsuru <GloomyGhost@GloomyGhost.com>

3e34a8c
```

https://user-images.githubusercontent.com/105754474/170843222-0c4a6ce7-d0db-4d1d-a9af-40cd59f1031b.mp4

**Comment by YuzukiTsuru** [comment]
According to src/openixcard/payloads, Android image is not supported at present, I still don't know the partition structure of Android image. It is a problem that no error is reported. Then I will try to fix it

**Comment by agevlakh** [comment]
Thank you very much for the information. If you need my help with testing, I'm ready to help.

**Comment by agevlakh** [comment]
Hello. This is article about android image structure for orange pi zero 2 on Russian language. You can use Google translate for reading it.
http://nskhuman.ru/allwinner/firmware.php
I hope it was helpful for your development.

С уважением,
Антон Евлах

**Comment by YuzukiTsuru** [comment]
Just bought the h616 development board and tried to adapt to Android conversion

**Comment by agevlakh** [comment]
Good luck in development!
Also I recommend read this article with translate. Maybe it helps:
http://nskhuman.ru/allwinner/firmware.php
