### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by broadwit** [YuzukiTsuru/OpenixCard#8]
错误如下：
penixCard/src/GenIMG/GenIMG.cpp:13:10: fatal error: filesystem: 没有那个文件或目录
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.

编译环境
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by YuzukiTsuru** [comment]
不支持gcc7，最低gcc9
